"use client";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowLeft,
  faArrowRight,
  faArrowTrendDown,
  faArrowTrendUp,
  faBagShopping,
  faBars,
  faBolt,
  faBoxesStacked,
  faBullhorn,
  faCalendarDays,
  faCamera,
  faChartColumn,
  faChartLine,
  faChartPie,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleQuestion,
  faCircleXmark,
  faClapperboard,
  faClock,
  faCoins,
  faComment,
  faComments,
  faCrown,
  faDatabase,
  faDiamond,
  faFilter,
  faFire,
  faGaugeHigh,
  faGift,
  faHandshake,
  faHashtag,
  faHeart,
  faLightbulb,
  faListCheck,
  faLock,
  faMagnifyingGlassChart,
  faMessage,
  faMinus,
  faMoneyBillTrendUp,
  faMoon,
  faPaperPlane,
  faPercent,
  faPlus,
  faRankingStar,
  faRobot,
  faRotateRight,
  faScaleBalanced,
  faSchool,
  faSearch,
  faShieldHalved,
  faStar,
  faStore,
  faTag,
  faThumbtack,
  faTriangleExclamation,
  faTrophy,
  faTruckFast,
  faUmbrellaBeach,
  faUserCheck,
  faUsers,
  faWandMagicSparkles,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

const ICONS: Record<string, IconDefinition> = {
  faArrowLeft,
  faArrowRight,
  faArrowTrendDown,
  faArrowTrendUp,
  faBagShopping,
  faBars,
  faBolt,
  faBoxesStacked,
  faBullhorn,
  faCalendarDays,
  faCamera,
  faChartColumn,
  faChartLine,
  faChartPie,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleQuestion,
  faCircleXmark,
  faClapperboard,
  faClock,
  faCoins,
  faComment,
  faComments,
  faCrown,
  faDatabase,
  faDiamond,
  faFilter,
  faFire,
  faGaugeHigh,
  faGift,
  faHandshake,
  faHashtag,
  faHeart,
  faLightbulb,
  faListCheck,
  faLock,
  faMagnifyingGlassChart,
  faMessage,
  faMinus,
  faMoneyBillTrendUp,
  faMoon,
  faPaperPlane,
  faPercent,
  faPlus,
  faRankingStar,
  faRobot,
  faRotateRight,
  faScaleBalanced,
  faSchool,
  faSearch,
  faShieldHalved,
  faStar,
  faStore,
  faTag,
  faThumbtack,
  faTriangleExclamation,
  faTrophy,
  faTruckFast,
  faUmbrellaBeach,
  faUserCheck,
  faUsers,
  faWandMagicSparkles,
  faXmark,
};

export function FaIcon({
  name,
  className,
  spin,
}: {
  name: string;
  className?: string;
  spin?: boolean;
}) {
  const icon = ICONS[name] ?? faCircleQuestion;
  return <FontAwesomeIcon icon={icon} className={className} spin={spin} />;
}
