name: Build and Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make re

    - name: Check --help exits 0
      run: ./stone_analysis --help && echo "PASS" || echo "FAIL"

    - name: Run tests
      run: |
        python3 tests/generate_wav.py
        bash tests/run_tests.sh
