import type { Product } from "@/types";

const now = new Date().toISOString();

/** Static preview data for the public landing page — not the real seed data (see supabase/migrations). */
export const MOCK_PREVIEW_PRODUCTS: Product[] = [
  {
    id: "preview-1",
    nom: "Brasero pliable en acier",
    description: "Brasero compact et pliable, parfait pour les soirées d'hiver en extérieur.",
    categorie: "Maison",
    image_url: "https://images.unsplash.com/photo-1628478078897-0944ef2a6fe3?w=640&q=60&auto=format&fit=crop",
    prix_conseille: 29900,
    marge_estimee: "45%",
    score: 92,
    pays_cible: ["US", "CA", "FR"],
    mois_pertinents: [11, 12, 1],
    public_cible: "Familles et amateurs de soirées extérieures",
    arguments_vente: [],
    angles_marketing: [],
    source: "seed",
    updated_at: now,
    created_at: now,
  },
  {
    id: "preview-2",
    nom: "Chauffage d'appoint céramique",
    description: "Chauffage silencieux et économe, très recherché pendant la saison froide.",
    categorie: "Maison",
    image_url: "https://images.unsplash.com/photo-1727797208736-6efdc1088f81?w=640&q=60&auto=format&fit=crop",
    prix_conseille: 25900,
    marge_estimee: "50%",
    score: 88,
    pays_cible: ["US", "CA", "FR"],
    mois_pertinents: [11, 12, 1, 2],
    public_cible: "Foyers cherchant un chauffage d'appoint mobile",
    arguments_vente: [],
    angles_marketing: [],
    source: "seed",
    updated_at: now,
    created_at: now,
  },
  {
    id: "preview-3",
    nom: "Guirlande lumineuse LED",
    description: "Éclairage de Noël personnalisable, un best-seller de la fin d'année.",
    categorie: "Maison",
    image_url: "https://images.unsplash.com/photo-1513297887119-d46091b24bfa?w=640&q=60&auto=format&fit=crop",
    prix_conseille: 14900,
    marge_estimee: "55%",
    score: 85,
    pays_cible: ["US", "CA"],
    mois_pertinents: [11, 12],
    public_cible: "Particuliers et décorateurs de fêtes",
    arguments_vente: [],
    angles_marketing: [],
    source: "seed",
    updated_at: now,
    created_at: now,
  },
];
