##
## EPITECH PROJECT, 2025
## make
## File description:
## file
##

SRC	=	MyCat.cpp

OPT	=	-std=c++20 -Wall -Wextra -Werror

NAME	=	MyCat

all:
	g++ $(SRC) -o $(NAME) $(OPT)

clean:
	rm -f $(NAME)

fclean: clean
	rm -f *~
	rm -f *#

re: fclean all