name: Continuous Integration

on:
  push:
    branches: [ "main", "will" ]
  pull_request:
    branches: [ "main", "will" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project/project

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install

    - name: Check Code Quality (Lint)
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Build Project
      run: npm run build
