import { Dimensions, StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const { height } = Dimensions.get('window');

const SOFT_SHADOW = {
  shadowColor: COLORS.shadow,
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.16,
  shadowRadius: 16,
  elevation: 8,
};

const SUBTLE_SHADOW = {
  shadowColor: COLORS.shadow,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 8,
  elevation: 4,
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  map: { flex: 1 },

  /* --- Overlay de chargement --- */
  loadingOverlay: {
    position: 'absolute',
    top: 76,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 1010,
  },
  loadingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    ...SUBTLE_SHADOW,
  },
  loadingPillText: {
    marginLeft: 8,
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.text,
    fontFamily: 'CenturyGothic',
  },

  /* --- Barre de recherche (pilule + GPS) --- */
  searchContainer: {
    position: 'absolute',
    top: 12,
    left: 14,
    right: 14,
    zIndex: 1006,
  },
  searchPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 30,
    height: 52,
    paddingLeft: 16,
    paddingRight: 6,
    ...SOFT_SHADOW,
  },
  searchInputZone: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchIcon: { fontSize: 15, marginRight: 8, opacity: 0.7 },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: COLORS.text,
    outlineStyle: 'none',
    fontFamily: 'CenturyGothic',
  },
  searchClear: { fontSize: 16, color: COLORS.textTertiary, paddingHorizontal: 6 },
  searchDivider: {
    width: 1,
    height: 24,
    backgroundColor: COLORS.border,
    marginHorizontal: 6,
  },
  gpsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gpsIcon: { fontSize: 20, color: COLORS.white, fontWeight: '700', lineHeight: 22 },

  /* --- Résultats de recherche --- */
  searchResults: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    marginTop: 8,
    maxHeight: 240,
    paddingVertical: 4,
    ...SOFT_SHADOW,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  searchResultIcon: { fontSize: 16, marginRight: 10 },
  searchResultText: { fontSize: 14, color: COLORS.text, fontFamily: 'CenturyGothic' },

  /* --- Sélecteur de ville (chip flottant) --- */
  villeBtn: {
    position: 'absolute',
    top: 76,
    left: 14,
    zIndex: 1005,
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    ...SUBTLE_SHADOW,
  },
  villeBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.primaryDark,
    marginLeft: 6,
    fontFamily: 'CenturyGothic',
  },
  villeBtnChevron: { fontSize: 10, color: COLORS.textTertiary, marginLeft: 6 },

  /* --- Onglets de couches --- */
  layerTabs: {
    position: 'absolute',
    top: 124,
    left: 0,
    right: 0,
    zIndex: 1005,
  },
  layerScroll: { paddingHorizontal: 14 },
  layerTab: {
    paddingHorizontal: 15,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    ...SUBTLE_SHADOW,
  },
  activeTab: { backgroundColor: COLORS.primary },
  tabText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginLeft: 6,
    fontFamily: 'CenturyGothic',
  },
  activeTabText: { color: COLORS.white },

  /* --- Contrôles flottants à droite (type de carte) --- */
  mapOptions: {
    position: 'absolute',
    top: 180,
    right: 14,
    zIndex: 1005,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 5,
    ...SUBTLE_SHADOW,
  },
  optionBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionBtnActive: { backgroundColor: COLORS.chipBg },
  optionIcon: { fontSize: 18 },
  optionDivider: { height: 1, backgroundColor: COLORS.border, marginVertical: 2, marginHorizontal: 6 },

  /* --- Bottom sheet --- */
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingBottom: 14,
    zIndex: 1004,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    elevation: 16,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: COLORS.border,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    marginBottom: 10,
  },
  sheetTitleWrap: { flexDirection: 'row', alignItems: 'center' },
  sheetTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.text,
    fontFamily: 'CenturyGothic',
  },
  sheetCountBadge: {
    marginLeft: 10,
    backgroundColor: COLORS.chipBg,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
  },
  sheetCountText: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.primaryDark,
    fontFamily: 'CenturyGothic',
  },
  sheetAnalyseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
  },
  sheetAnalyseText: {
    color: COLORS.white,
    fontSize: 12.5,
    fontWeight: '700',
    fontFamily: 'CenturyGothic',
  },

  /* --- Filtres (dans le bottom sheet) --- */
  bottomControls: { marginTop: 2 },
  filterScroll: { paddingHorizontal: 14, marginBottom: 8 },
  filterChip: {
    backgroundColor: COLORS.backgroundAlt,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  activeFilterChip: { backgroundColor: COLORS.primary },
  filterText: { fontSize: 12.5, fontWeight: '700', color: COLORS.textSecondary, fontFamily: 'CenturyGothic' },
  activeFilterText: { color: COLORS.white },
  statusChip: {
    backgroundColor: COLORS.backgroundAlt,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },

  /* --- Callouts (popups markers) --- */
  calloutCard: {
    width: 230,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    overflow: 'hidden',
  },
  calloutHeader: { paddingVertical: 9, paddingHorizontal: 12, alignItems: 'center' },
  calloutTitle: { color: COLORS.white, fontWeight: '800', fontSize: 13, fontFamily: 'CenturyGothic' },
  calloutBody: { padding: 12 },
  calloutDesc: { fontSize: 13, color: COLORS.text, marginBottom: 8, lineHeight: 18, fontFamily: 'CenturyGothic' },
  calloutDate: { fontSize: 11, color: COLORS.textTertiary, textAlign: 'right', fontFamily: 'CenturyGothic' },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  infoLabel: { fontWeight: '700', width: 84, fontSize: 14, color: COLORS.text, fontFamily: 'CenturyGothic' },
  infoValue: { fontSize: 14, color: COLORS.textSecondary, flex: 1, fontFamily: 'CenturyGothic' },
  emptyFilterText: { textAlign: 'center', color: COLORS.textSecondary, padding: 14, fontSize: 13, fontFamily: 'CenturyGothic' },

  /* --- Modale détail (carte façon "fiche") --- */
  modalBg: { flex: 1, backgroundColor: COLORS.overlay, justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    padding: 20,
    paddingTop: 14,
    maxHeight: height * 0.78,
  },
  modalClose: {
    position: 'absolute',
    top: 14,
    right: 16,
    zIndex: 5,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.backgroundAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseText: { fontSize: 15, color: COLORS.textSecondary, fontWeight: '700', fontFamily: 'CenturyGothic' },
  modalTitle: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: COLORS.textTertiary,
    marginBottom: 12,
    fontFamily: 'CenturyGothic',
  },
  modalBadge: {
    alignSelf: 'flex-start',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 14,
  },
  modalBadgeText: { color: COLORS.white, fontWeight: '800', fontSize: 13, fontFamily: 'CenturyGothic' },
  modalImage: {
    width: '100%',
    height: 160,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: COLORS.backgroundAlt,
  },
  modalBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: 15,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 18,
  },
  modalBtnText: { color: COLORS.white, fontWeight: '800', fontSize: 15, fontFamily: 'CenturyGothic' },
});
